### ISSUE TITLE
Splash Screen does not apply transition at the end of the animation

### ISSUE THREAD

**Issue by Paul9834** [waseefakhtar/MotionLayoutTwitter#1]
No input transition does not apply when you try to change Activity

[Video here](https://twitter.com/Paul9834/status/1278046416292716544)

**Comment by waseefakhtar** [comment]
Thanks for the report! Is it the black screen that you get after the transition is completed? Does it not move to the next activity unless you close the app and open again?

Also, have you tried running it on an emulator? My wild guess is that that could happen on some devices because MotionLayout is still in beta, but I'd still like to investigate this.

**Comment by Paul9834** [comment]
> Gracias por el informe! ¿Es la pantalla negra que obtienes después de completar la transición? ¿No pasa a la siguiente actividad a menos que cierre la aplicación y vuelva a abrirla?
> 
> Además, ¿has intentado ejecutarlo en un emulador? Mi conjetura es que eso podría suceder en algunos dispositivos porque MotionLayout todavía está en beta, pero todavía me gustaría investigar esto.

That's right, it happens when the transition is complete, it is correct it does not go to the next activity unless you minimize and reopen the application. No, don't try testing on the emulator, it was tester on Samsung Galaxy S7 phone with API 26

**Comment by waseefakhtar** [comment]
> > Gracias por el informe! ¿Es la pantalla negra que obtienes después de completar la transición? ¿No pasa a la siguiente actividad a menos que cierre la aplicación y vuelva a abrirla?
> > Además, ¿has intentado ejecutarlo en un emulador? Mi conjetura es que eso podría suceder en algunos dispositivos porque MotionLayout todavía está en beta, pero todavía me gustaría investigar esto.
> 
> That's right, it happens when the transition is complete, it is correct it does not go to the next activity unless you minimize and reopen the application. No, don't try testing on the emulator, it was tester on Samsung Galaxy S7 phone with API 26

Right. I just tested it on an emulator and on Galaxy A10 and I can't reproduce the issue. :( In any case that I do, I'd love to solve it. But feel free to create a new PR if you happen to solve it yourself.

**Comment by Paul9834** [comment]
Very strange I do not want to affirm is that it is on the part of the Samsung system, but I suspect that it is from there, I will try to find and achieve a solution

**Comment by Paul9834** [comment]
> > > Gracias por el informe! ¿Es la pantalla negra que obtienes después de completar la transición? ¿No pasa a la siguiente actividad a menos que cierre la aplicación y vuelva a abrirla?
> > > Además, ¿has intentado ejecutarlo en un emulador? Mi conjetura es que eso podría suceder en algunos dispositivos porque MotionLayout todavía está en beta, pero todavía me gustaría investigar esto.
> > 
> > 
> > That's right, it happens when the transition is complete, it is correct it does not go to the next activity unless you minimize and reopen the application. No, don't try testing on the emulator, it was tester on Samsung Galaxy S7 phone with API 26
> 
> Right. I just tested it on an emulator and on Galaxy A10 and I can't reproduce the issue. :( In any case that I do, I'd love to solve it. But feel free to create a new PR if you happen to solve it yourself.

Very strange I do not want to affirm is that it is on the part of the Samsung system, but I suspect that it is from there, I will try to find and achieve a solution

**Comment by Paul9834** [comment]
The problem was solved and I made a pull request

**Comment by Paul9834** [comment]
The problem was solved and I made a pull request
https://github.com/Paul9834/MotionLayoutTwitter/commit/3c24b5739a610028ff931cbda0214e8c79ee3473
